services:
  api:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./api:/api
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/frontend
    command: npm start